from typing import TypeVar, Generic

_T_CELL = TypeVar("_T_CELL")

class Cell(Generic[_T_CELL]):
    def __init__(self, value: _T_CELL, following: Cell[_T_CELL] | None = None) -> None: ...
    def clone(self) -> Cell[_T_CELL]: ...
    @property
    def value(self) -> _T_CELL: ...
    @property
    def following(self) -> Cell[_T_CELL] | None: ...
    def set_following(self, new: Cell[_T_CELL]) -> None: ...
    def to_list(self) -> list[_T_CELL]: ...
    def go(self, steps: int) -> Cell[_T_CELL]: ...

def new_from(values: list[_T_CELL]) -> Cell[_T_CELL]: ...
