from structures_detroix23.modules import cell as cell
from typing import TypeVar, Generic, Optional

_T_LIST = TypeVar("_T_LIST")

class DynamicList(Generic[_T_LIST]):
    data: Optional[cell.Cell[_T_LIST]]
    def __init__(self, data: Optional[cell.Cell[_T_LIST]] = None) -> None: ...
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def to_list(self) -> list[_T_LIST]: ...
    def get_last(self) -> cell.Cell[_T_LIST]: ...
    def push(self, new: cell.Cell[_T_LIST]) -> None: ...
    def append(self, value: _T_LIST) -> None: ...
