from structures_detroix23.modules.types import Weight as Weight
from typing import Optional, Iterable, Self

class Node:
    def __new__(cls, name: str, previous: Optional[dict['Node', Weight]] = None, next: Optional[dict['Node', Weight]] = None) -> Self: ...
    def __init__(self, name: str, previous: dict['Node', Weight] | None = None, next: dict['Node', Weight] | None = None) -> None: ...
    def __hash__(self) -> int: ...
    def get_id(self) -> int: ...
    def get_name(self) -> str: ...
    def get_previous(self) -> dict['Node', Weight]: ...
    def get_next(self) -> dict['Node', Weight]: ...
    def set_previous(self, node: Node, weight: Weight) -> None: ...
    def set_next(self, node: Node, weight: Weight) -> None: ...
    def batch_previous(self, nodes: Iterable[tuple['Node', Weight]]) -> None: ...
    def batch_next(self, nodes: Iterable[tuple['Node', Weight]]) -> None: ...
    def remove_previous(self, node: Node) -> Optional[Weight]: ...
    def remove_next(self, node: Node) -> Optional[Weight]: ...
    def display(self, tab: str, level: int = 0, seen: Optional[set['Node']] = None) -> str: ...

def pretty(iterable: dict['Node', Weight], seen: set['Node'], tab: str = '\t', level: int = 0) -> str: ...
